
CREATE TABLE VOTES (
    VoteId INT IDENTITY(1,1) PRIMARY KEY,
    User_Id VARCHAR(100),
    AnswerId VARCHAR(100),
    FOREIGN KEY (User_Id) REFERENCES USERS(User_Id),
    FOREIGN KEY (AnswerId) REFERENCES ANSWERS(AnswerId)
);
