
CREATE TABLE COMMENT (
  CommentId VARCHAR(100)  PRIMARY KEY,
  Comment TEXT NOT NULL,
  CreationDate DATETIME NOT NULL,
  User_Id VARCHAR(100) NOT NULL,
  QuestionId VARCHAR(100)  NOT NULL,
  FOREIGN KEY (User_Id) REFERENCES Users(User_Id),
  FOREIGN KEY ( QuestionId) REFERENCES QUESTIONS(QuestionId) 
     ON DELETE CASCADE,
);